replicaCount: 1

image:
  repository: khushi08yadav/new-postgres-k8s
  tag: "9eda1f"
  pullPolicy: IfNotPresent

postgres:
  db: postgres_db
  user: db_admin
  password: dbpassword
  storage:
    size: 10Gi
    storageClass: standard

service:
  type: LoadBalancer
  port: 5432
