apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: "postgres-db"
  namespace: postgresql

spec:
  serviceName: "postgres-service"
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: postgres-db

  template:
    metadata:
      labels:
        app: postgres-db

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}

          ports:
            - containerPort: 5432
              name: postgres

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
      - metadata:
          name: postgres-data

        spec:
          accessModes: [ "ReadWriteOnce" ]

          resources:
            requests:
              storage: {{ .Values.postgres.storage.size }}
          
          storageClassName: {{ .Values.postgres.storage.storageClass }}
